"""adiciona pagamentos e eventos; migra dinheiro para centavos

Revision ID: a9062629ea07
Revises: fde58c624dd5
Create Date: 2026-07-29 22:24:22.678881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9062629ea07'
down_revision: Union[str, Sequence[str], None] = 'fde58c624dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_pagamento_external_event_id'), 'eventos_pagamento', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_eventos_pagamento_external_id'), 'eventos_pagamento', ['external_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'FALHOU', 'EXPIRADO', 'ESTORNADO', name='status_pagamento'), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('qr_code', sa.String(length=4096), nullable=True),
    sa.Column('copia_e_cola', sa.String(length=1024), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_external_id'), 'pagamentos', ['external_id'], unique=True)
    op.create_index(op.f('ix_pagamentos_pedido_id'), 'pagamentos', ['pedido_id'], unique=True)
    # Dinheiro passa a ser inteiro em centavos. batch_alter_table funciona tanto
    # no PostgreSQL quanto no SQLite (que não suporta ALTER COLUMN TYPE direto).
    with op.batch_alter_table("itens_pedido") as batch:
        batch.alter_column(
            "preco_unitario",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Integer(),
            existing_nullable=False,
        )
    with op.batch_alter_table("pedidos") as batch:
        batch.alter_column(
            "total",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Integer(),
            existing_nullable=False,
        )
    with op.batch_alter_table("produtos") as batch:
        batch.alter_column(
            "preco",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Integer(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("produtos") as batch:
        batch.alter_column(
            "preco",
            existing_type=sa.Integer(),
            type_=sa.NUMERIC(precision=12, scale=2),
            existing_nullable=False,
        )
    with op.batch_alter_table("pedidos") as batch:
        batch.alter_column(
            "total",
            existing_type=sa.Integer(),
            type_=sa.NUMERIC(precision=12, scale=2),
            existing_nullable=False,
        )
    with op.batch_alter_table("itens_pedido") as batch:
        batch.alter_column(
            "preco_unitario",
            existing_type=sa.Integer(),
            type_=sa.NUMERIC(precision=12, scale=2),
            existing_nullable=False,
        )
    op.drop_index(op.f('ix_pagamentos_pedido_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_external_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_eventos_pagamento_external_id'), table_name='eventos_pagamento')
    op.drop_index(op.f('ix_eventos_pagamento_external_event_id'), table_name='eventos_pagamento')
    op.drop_table('eventos_pagamento')
    # ### end Alembic commands ###
